#define DSS_BASE			(0x48050000)
#define DSS_SYSCONFIG		(DSS_BASE + 0x0010)

#define DISPC_BASE			0x48050400

/* DISPC common */
#define DISPC_REVISION			(DISPC_BASE + 0x0000)
#define DISPC_SYSCONFIG			(DISPC_BASE + 0x0010)
#define DISPC_SYSSTATUS			(DISPC_BASE + 0x0014)
#define DISPC_IRQSTATUS			(DISPC_BASE + 0x0018)
#define DISPC_IRQENABLE			(DISPC_BASE + 0x001C)
#define DISPC_CONTROL			(DISPC_BASE + 0x0040)
#define DISPC_CONFIG		    (DISPC_BASE + 0x0044)
#define DISPC_CAPABLE			(DISPC_BASE + 0x0048)
#define DISPC_DEFAULT_COLOR0	(DISPC_BASE + 0x004C)
#define DISPC_DEFAULT_COLOR1	(DISPC_BASE + 0x0050)
#define DISPC_TRANS_COLOR0		(DISPC_BASE + 0x0054)
#define DISPC_TRANS_COLOR1		(DISPC_BASE + 0x0058)
#define DISPC_LINE_STATUS		(DISPC_BASE + 0x005C)
#define DISPC_LINE_NUMBER		(DISPC_BASE + 0x0060)
#define DISPC_TIMING_H			(DISPC_BASE + 0x0064)
#define DISPC_TIMING_V			(DISPC_BASE + 0x0068)
#define DISPC_POL_FREQ			(DISPC_BASE + 0x006C)
#define DISPC_DIVISOR			(DISPC_BASE + 0x0070)
#define DISPC_SIZE_DIG			(DISPC_BASE + 0x0078)
#define DISPC_SIZE_LCD			(DISPC_BASE + 0x007C)

#define DISPC_DATA_CYCLE1		(DISPC_BASE + 0x01D4)
#define DISPC_DATA_CYCLE2		(DISPC_BASE + 0x01D8)
#define DISPC_DATA_CYCLE3		(DISPC_BASE + 0x01DC)

/* DISPC GFX plane */
#define DISPC_GFX_BA0			    (DISPC_BASE + 0x0080)
#define DISPC_GFX_BA1			    (DISPC_BASE + 0x0084)
#define DISPC_GFX_POSITION		    (DISPC_BASE + 0x0088)
#define DISPC_GFX_SIZE			    (DISPC_BASE + 0x008C)
#define DISPC_GFX_ATTRIBUTES		(DISPC_BASE + 0x00A0)
#define DISPC_GFX_FIFO_THRESHOLD	(DISPC_BASE + 0x00A4)
#define DISPC_GFX_FIFO_SIZE_STATUS	(DISPC_BASE + 0x00A8)
#define DISPC_GFX_ROW_INC		    (DISPC_BASE + 0x00AC)
#define DISPC_GFX_PIXEL_INC		    (DISPC_BASE + 0x00B0)
#define DISPC_GFX_WINDOW_SKIP	    (DISPC_BASE + 0x00B4)
#define DISPC_GFX_TABLE_BA		    (DISPC_BASE + 0x00B8)

/* DISPC Video plane 1/2 */
#define DISPC_VID1_BASE			(DISPC_BASE + 0x00BC)
#define DISPC_VID2_BASE			(DISPC_BASE + 0x014C)

/* Offsets into DISPC_VID1/2_BASE */
#define DISPC_VID_BA0			0x0000
#define DISPC_VID_BA1			0x0004
#define DISPC_VID_POSITION		0x0008
#define DISPC_VID_SIZE			0x000C
#define DISPC_VID_ATTRIBUTES		0x0010
#define DISPC_VID_FIFO_THRESHOLD	0x0014
#define DISPC_VID_FIFO_SIZE_STATUS	0x0018
#define DISPC_VID_ROW_INC		0x001C
#define DISPC_VID_PIXEL_INC		0x0020
#define DISPC_VID_FIR			0x0024
#define DISPC_VID_PICTURE_SIZE		0x0028
#define DISPC_VID_ACCU0			0x002C
#define DISPC_VID_ACCU1			0x0030

/* 8 elements in 8 byte increments */
#define DISPC_VID_FIR_COEF_H0		0x0034
/* 8 elements in 8 byte increments */
#define DISPC_VID_FIR_COEF_HV0		0x0038
/* 5 elements in 4 byte increments */
#define DISPC_VID_CONV_COEF0		0x0074

#define DISPC_IRQ_FRAMEMASK		0x0001
#define DISPC_IRQ_VSYNC			0x0002
#define DISPC_IRQ_EVSYNC_EVEN		0x0004
#define DISPC_IRQ_EVSYNC_ODD		0x0008
#define DISPC_IRQ_ACBIAS_COUNT_STAT	0x0010
#define DISPC_IRQ_PROG_LINE_NUM		0x0020
#define DISPC_IRQ_GFX_FIFO_UNDERFLOW	0x0040
#define DISPC_IRQ_GFX_END_WIN		0x0080
#define DISPC_IRQ_PAL_GAMMA_MASK	0x0100
#define DISPC_IRQ_OCP_ERR		0x0200
#define DISPC_IRQ_VID1_FIFO_UNDERFLOW	0x0400
#define DISPC_IRQ_VID1_END_WIN		0x0800
#define DISPC_IRQ_VID2_FIFO_UNDERFLOW	0x1000
#define DISPC_IRQ_VID2_END_WIN		0x2000
#define DISPC_IRQ_SYNC_LOST		0x4000

#define DISPC_IRQ_MASK_ALL		0x7fff

#define DISPC_IRQ_MASK_ERROR		(DISPC_IRQ_GFX_FIFO_UNDERFLOW |	\
					     DISPC_IRQ_VID1_FIFO_UNDERFLOW | \
					     DISPC_IRQ_VID2_FIFO_UNDERFLOW | \
					     DISPC_IRQ_SYNC_LOST)
// Register fields

// DSS_SYSCONFIG

#define DSS_SYSCONFIG_SOFT_RESET_MASK           (1)
#define DSS_SYSCONFIG_SOFT_RESET_SHIFT          (1)
#define DSS_SYSCONFIG_SOFT_RESET_RESET          (1)

#define DSS_SYSCONFIG_AUTO_IDLE_MASK            (1)
#define DSS_SYSCONFIG_AUTO_IDLE_SHIFT           (0)
#define DSS_SYSCONFIG_AUTO_IDLE_ON              (1)
#define DSS_SYSCONFIG_AUTO_IDLE_OFF             (0)

////// DSS_SYSTATUS register bit fields /////////////////////

#define DSS_SYSSTATUS_RESET_DONE_MASK           (1)
#define DSS_SYSSTATUS_RESET_DONE_SHIFT          (0)
#define DSS_SYSSTATUS_RESET_DONE_DONE           (1)
#define DSS_SYSSTATUS_RESET_DONE_NOT_DONE       (0)

////// DSS_IRQSTATUS register bit fields /////////////////////

#define DSS_IRQSTATUS_DISPC_MASK           (1)
#define DSS_IRQSTATUS_DISPC_SHIFT          (0)
#define DSS_IRQSTATUS_DISPC_ACTIVE         (1)
#define DSS_IRQSTATUS_DISPC_NOTACTIVE      (0)

#define DSS_IRQSTATUS_DSI_MASK           (1)
#define DSS_IRQSTATUS_DSI_SHIFT          (1)
#define DSS_IRQSTATUS_DSI_ACTIVE         (1)
#define DSS_IRQSTATUS_DSI_NOTACTIVE      (0)

////// DSS_CONTROL register bit fields ////////////////////////

#define DSS_CONTOL_DISPC_CLK_MASK           (1)
#define DSS_CONTOL_DISPC_CLK_SHIFT          (0)
#define DSS_CONTOL_DISPC_CLD_ALWON_FCLK     (0)
#define DSS_CONTOL_DISPC_DSI1_PLL_FCLK      (1)




